--- 
- name: 파일 배포 예제
  hosts: all
  gather_facts: yes
  vars:
    system_owner: webmaster@example.com
  tasks:
    - name: 파일 배포 - /etc/motd
      template: 
        src: templates/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'
        