---
- name: /etc/hosts 파일 생성
  hosts: all
  gather_facts: no
  tasks:
    - name: 파일 복사 - /etc/hosts
      copy:
        src: files/hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: '0644'