---
- name: 파일 배포
  hosts: all
  tasks:
    - name: /etc/issue 파일 배포
      template:
        src: templeates/issue.j2
        dest: /etc/issue
        owner: root
        group: root
        mode: '0644'