---
- name: 웹 서버 구성
  hosts: webservers
  gather_facts: true
  tasks:
    # 1. 패키지 설치 - httpd, firewalld
    - name: 패키지 설치
      yum:
        name:
          - httpd
          - firewalld
        state: present
      
    # 2. 서비스 설정 - /var/www/html/hello.html
    - name: 서비스 설정
     template:
        src: templates/hello.html
        dest: /var/www/html/hello.html
        
    # 3. 서비스 기동 - httpd, firewalld
    - name: 서비스 기동
      service: 
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - httpd
        - firewalld
      
    # 4. 방화벽 서비스 포트 등록 - http, https
    - name: 방화벽 서비스 포트 등록 
      firewalld:
        service: "{{ item }}"
        zone: public
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - http
        - https
        