---
- name: 로그 수집 예제
  hosts: all
  gather_facts: no
  tasks: 
    # 작업 시나리오
    # (a1/a2/a3/a3) /var/log/secure --> (a) secure-backups/
    - name: 로그 파일 수집 - /var/log/secure
      fetch:
        src: /var/log/secure
        dest: secure-backups/{{ inventory_hostname }}-secure
        flat: yes
