---
- name: 시간 동기화
  hosts: datacenters

  roles: 
    - rhel-system-roles.timesync

  post_tasks:
    - name: 타임존 설정
      timezone: 
        name: "{{ host_timezone }}"
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      service:
        name: chronyd
        state: restarted 
